// <auto-generated />
namespace WPF_Mvvm_and_EF.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedProgrammingLanguage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedProgrammingLanguage));
        
        string IMigrationMetadata.Id
        {
            get { return "201902041455497_addedProgrammingLanguage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
